name: Rebuild Vagrant Cluster
on:
  push:
    paths:
      - 'Vagrantfile'  # Запуск только при изменении Vagrantfile

jobs:
  rebuild-vagrant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Save SSH keys
        run: |
          # Создаем папку .ssh
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Восстанавливаем публичный ключ (для Vagrant)
          echo "${{ secrets.VAGRANT_SSH_PUB_KEY }}" | base64 -d > ~/.ssh/vagrant_ansible_key.pub
          chmod 644 ~/.ssh/vagrant_ansible_key.pub

          # Восстанавливаем приватный ключ (для Ansible)
          echo "${{ secrets.VAGRANT_SSH_PRIV_KEY }}" | base64 -d > ~/.ssh/vagrant_ansible_key
          chmod 600 ~/.ssh/vagrant_ansible_key

      - name: Install Vagrant and VirtualBox
        run: |
          sudo apt-get update
          sudo apt-get install -y vagrant virtualbox

      - name: Start and provision VMs
        run: |
          vagrant destroy -f || true  # Игнорируем ошибки, если VM нет
          vagrant up
