name: Rebuild Vagrant Cluster
on:
  push:
    paths:
      - 'Vagrantfile'  # Запуск только при изменении Vagrantfile

jobs:
  rebuild-vagrant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Save SSH keys
        run: |
          # Создаем папку .ssh
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Восстанавливаем публичный ключ (для Vagrant)
          echo "${{ secrets.VAGRANT_SSH_PUB_KEY }}" | base64 -d > ~/.ssh/vagrant_ansible_key.pub
          chmod 644 ~/.ssh/vagrant_ansible_key.pub

          # Восстанавливаем приватный ключ (для Ansible)
          echo "${{ secrets.VAGRANT_SSH_PRIV_KEY }}" | base64 -d > ~/.ssh/vagrant_ansible_key
          chmod 600 ~/.ssh/vagrant_ansible_key

      - name: Install Vagrant and VirtualBox and Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y vagrant virtualbox ansible

      - name: Run deployment script
        run: |
          chmod +x deploy_infra.sh
          ./deploy_infra.sh "git@github.com:soldatviktimnosti/VagrantMachine.git" "git@github.com:soldatviktimnosti/ansible.git"

